# Generated by Django 2.1.7 on 2019-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
