# Generated by Django 2.1.7 on 2019-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.CharField(blank=True, choices=[('COMEDY', 'Comedy'), ('SCI-FI', 'Sci-fi'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('THRILLER', 'Thriller'), ('DRAMA', 'Drama'), ('MYSTERY', 'Mystery'), ('CRIME', 'Crime'), ('ANIMATION', 'Animation'), ('ADVENTURE', 'Adventure'), ('FANTASY', 'Fantasy'), ('COMEDY-ROMANCE', 'Comedy-romance'), ('ACTION-COMEDY', 'Action-comedy'), ('SUPERHERO', 'Superhero')], default='COMEDY', max_length=20),
        ),
    ]
