# Generated by Django 2.1.7 on 2019-03-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20190314_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='imdb.Actor'),
        ),
    ]
