# Generated by Django 2.1.7 on 2019-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20190314_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
