# Generated by Django 2.1.7 on 2019-03-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_auto_20190314_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assign', models.DateTimeField()),
                ('actor_award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Actor')),
                ('movie_award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='kind',
        ),
        migrations.AddField(
            model_name='award',
            name='kind',
            field=models.ManyToManyField(to='imdb.AwardKind'),
        ),
    ]
