# Generated by Django 2.1.7 on 2019-03-14 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_auto_20190314_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardkind',
            name='actor_award',
        ),
        migrations.RemoveField(
            model_name='awardkind',
            name='movie_award',
        ),
        migrations.RemoveField(
            model_name='award',
            name='kind',
        ),
        migrations.AddField(
            model_name='award',
            name='actor_kind',
            field=models.ManyToManyField(to='imdb.Actor'),
        ),
        migrations.AddField(
            model_name='award',
            name='date_assign',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='movie_kind',
            field=models.ManyToManyField(to='imdb.Movie'),
        ),
        migrations.DeleteModel(
            name='AwardKind',
        ),
    ]
