# Generated by Django 2.1.7 on 2019-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_auto_20190314_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='kind',
            field=models.CharField(choices=[('ACTOR', 'Actor'), ('MOVIE', 'Movie')], default='ACTOR', max_length=50),
        ),
    ]
