# Generated by Django 2.1.7 on 2019-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0009_award_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='actor_kind',
            field=models.ManyToManyField(blank=True, to='imdb.Actor'),
        ),
        migrations.AlterField(
            model_name='award',
            name='movie_kind',
            field=models.ManyToManyField(blank=True, to='imdb.Movie'),
        ),
    ]
